### ISSUE TITLE
Clarify exactly what Ammo WASM build we should use...

### ISSUE THREAD

**Issue by diarmidmackenzie** [c-frame/aframe-physics-system#16]
From  [@vincentfretin comments ](https://github.com/c-frame/aframe-physics-system/pull/14#issuecomment-1312453267)in PR #14... 

In [AmmoDriver.md](https://github.com/c-frame/aframe-physics-system/blob/eccbe03bdc3f7c56b97d084cbef8f1538b0033ac/AmmoDriver.md#including-the-ammojs-build) we talk about the ammo.js mozilla fork and the original kripken repo
http://kripken.github.io/ammo.js/builds/ammo.wasm.js
https://github.com/kripken/ammo.js
there are some recent commits in this repo https://github.com/kripken/ammo.js/commits/main

I see that in all examples we use
https://mixedreality.mozilla.org/ammo.js/builds/ammo.wasm.js
it doesn't seem to be the same build as the hubs branch in https://github.com/mozillareality/ammo.js
Do you know from which code source this build comes from?
Are we sure it's still an up to date version or should we switch back to a build from the original kripken repo?

from https://github.com/MozillaReality/ammo.js/tree/hubs/master/builds latest build from Dec 9, 2019
```sh
$ md5sum ammo.wasm.*
b9fad0a49e64f4fa99fe43aa1fb85de3  ammo.wasm.js
8640fe8d5bf91d2e84ea56e0c1307ba9  ammo.wasm.wasm
```
Hubs is using this build, https://github.com/mozilla/hubs/blob/master/package.json#L78
```sh
hubs (master) $ ag ammo.js src/
src/systems/physics-system.js
4:import ammoWasmUrl from "ammo.js/builds/ammo.wasm.wasm";
```

from https://mixedreality.mozilla.org/ammo.js/builds/
```sh
$ md5sum ammo.wasm.*
96789d18db20709b41f5ecfe607b5b51  ammo.wasm.js
0dc6487e17ff5e126cf6c925f5f04f35  ammo.wasm.wasm
```
It's actually an old version, the md5sum matches the build from May 9, 2019

So the link https://mixedreality.mozilla.org/ammo.js/builds/ammo.wasm.js is an old build from
https://github.com/MozillaReality/ammo.js/commits/hubs/master May 9, 2019, not the latest version Dec 11, 2019 that Hubs is using right now.

Short term, we should make sure it aligns with the docs (as long as the docs point somewhere sensible).

Longer term, we should consider making & maintaining our own fork of Ammo. Before doing that, though, I want to do more evaluation of PhysX. Given PhysX seems to perform better & APIs seem easier to work with than Ammo, it's not clear to me that long term it's going to make sense to put effort into maintaining both of them...

**Comment by vincentfretin** [comment]
We can replace in the examples
https://mixedreality.mozilla.org/ammo.js/builds/ammo.wasm.js
by
https://cdn.jsdelivr.net/gh/MozillaReality/ammo.js@8bbc0ea/builds/ammo.wasm.js
to have the Dec 11, 2019 build from the hubs fork

We could also fork hubs ammo.js repo, merge the changes from latest kripken, do our own build.
I looked quickly at the commits from january 2019 until now, the change are mostly about wasm build toolchain, and exposing some additional api https://github.com/kripken/ammo.js/pull/395 and https://github.com/kripken/ammo.js/pull/401 for example.
I personally won't spend time trying to have a new build with latest changes simply because I don't use ammo myself, but if there is interest on those new api, you know it's there.

**Comment by vincentfretin** [comment]
see https://github.com/n5ro/aframe-physics-system/issues/207
we should update README and example to use
https://cdn.jsdelivr.net/gh/MozillaReality/ammo.js@8bbc0ea/builds/ammo.wasm.js
